inmanta/inmanta-core

docs/conf.py, docs/config.rst, integration/integration.py, src/inmanta/agent/__init__.py, src/inmanta/agent/agent.py, src/inmanta/agent/config.py, src/inmanta/agent/io/remote.py, src/inmanta/app.py, src/inmanta/ast/statements/call.py, src/inmanta/client.py, src/inmanta/config.py, src/inmanta/export.py, src/inmanta/protocol.py, src/inmanta/server/__init__.py, src/inmanta/server/config.py, src/inmanta/server/server.py, src/inmanta/sphinxext.py, tests/test_2way_protocol.py, tests/test_server_agent.py
Config is now expected to be defined prior to use. 
To define a config option
`cfg_env = Option("config", "environment", None, "The environment this model is associated with", is_uuid_opt)`
to get the option
`cfg_env.get()`
Major changes:
- config options are returned as the type given in the definition, not longer as strings
- '-' and '_' are equivalent in config options
- server is moved from a file to a directory
fixes #156
=> Refactoring of the configuration framework to allow autogeneration of config docs 

src/inmanta/server/agentmanager.py
fixes #13 
moved state dir for server side agents from  `{server-state-dir}/agent`
to  `{server-state-dir}/{env-id}/agent`
=> isolated virtual envs for different agents started on the same server

src/inmanta/agent/agent.py, src/inmanta/agent/config.py, src/inmanta/protocol.py, src/inmanta/server/config.py
=> added server-timeout config option

src/inmanta/ast/entity.py, src/inmanta/ast/variables.py, tests/test_compilation.py, tests/test_server_agent.py
Indexing was broken due to mixing of repr and str on instances
triggered by new error reporting mechanism
=> Fixed critical bug in index mechanism

src/inmanta/agent/agent.py, src/inmanta/const.py, src/inmanta/export.py, src/inmanta/methods.py, src/inmanta/protocol.py, src/inmanta/server/server.py, tests/conftest.py, tests/test_compiler.py, tests/test_export.py, tests/test_server_agent.py
Previously all unknown handling was done in the server. This resulted in
strange reporting as the number of managed resource could go up and
down. Now, an additional resource state "unknown" is introduced. This
state is handled similar to skipped during deploys.
=> Add an unknown state to the server

src/inmanta/ast/attribute.py, src/inmanta/ast/entity.py, src/inmanta/ast/statements/__init__.py, src/inmanta/ast/statements/define.py, src/inmanta/module.py, tests/test_compilation.py, tests/test_compiler.py
Now the annotation is available as a string reference on the both ends
of the relation attribute
=> Add relation annotations to the relation attribute

src/inmanta/export.py, src/inmanta/resources.py, tests/data/modules/test/model/_init.cf, tests/data/modules/test/module.yml, tests/test_server_agent.py
This check raises an compiler exception when a resource id is not unique
=> Raise an exception when duplicate resources are exported

src/inmanta/agent/io/remote.py
tested solution for zombie processes created by execnet,
problem was that execnet does resource cleanup per gateway group and not per gateway, this caused zombie processes 
see: http://execnet.readthedocs.io/en/latest/basics.html#grouped-gateways-and-robust-termination
testcase:
```
#many agents
for aid in std::sequence(10):
agent = std::AgentConfig(autostart=true, agentname="agent{{aid}}", uri="ssh://centos@192.168.2.27")
host = std::Host(name=agent.agentname, os=std::linux)
#hammer them!
for fid in std::sequence(100):
std::ConfigFile(host=host, path="/tmp/a{{agent.agentname}}f{{fid}}", content="a")
end
end
#bad agents (kill agent)
for aid in std::sequence(3):
agent = std::AgentConfig(autostart=true, agentname="bagent{{aid}}", uri="ssh://centos@192.168.2.27:223")
host = …
```
=> fixed execnet resource leak

src/inmanta/agent/handler.py
Currently read_resource gets a clone of the desired state. If the
desired state requests purged=true, often a handler developer forgets to
manually set it to false. (because resourcepurged exception is most
often used)
This sets the default value for a clone to false for purged.
=> Set purged=false on clone in CRUDHandler

src/inmanta/ast/statements/assign.py, src/inmanta/ast/statements/generator.py, tests/test_compiler_errors.py
When a relation was assigned an instance of a wrong type inside the
constructor an error was caused during the generation of the error
message. This refactor handles the both cases + adds test cases
Fixes #557
=> Fix error message for wrong type in ctor

tests/test_compilation.py
current situation:
[0:1] -- A  is in java terms Optional[A] (accessing it with no value is
an error, it has either one value or is invalid)
[:1] -- A is in java terms Set[A] (it may contain any number of values
including none)
we should decide:
1- do we retain the behavior of [0:1] as optional
2- do we need a construct that is 'list with one or 0 values' that can
always be assigned to lists, but only to single valued variables if it
has a value  (if we have such a construct, does it work the same on +=
and =)
3- do we need a construct that is 'list with one or 0 values' that can
always be assigned (i.e. no direct warning on usage of empty optional)
see #608
=> empty optionals 

src/inmanta/ast/statements/assign.py, tests/test_compiler_errors.py
=> improved error reporting on bad assignment

src/inmanta/server/server.py, tests/test_server_agent.py
- no longer replace empty facts with ' '
fixes #731
=> Correctly store and report empty facts

src/inmanta/data.py
The index allows mongo to stream the data instead of having to sort it
in memory.
=> Add start to the index for the get_log query

src/inmanta/const.py, src/inmanta/export.py, src/inmanta/server/server.py, tests/conftest.py, tests/test_export.py, tests/test_resource.py, tests/test_server.py
=> prevent purge_on_delete due to failed compile

requirements.txt, tox.ini
3 plugins added, pyup will pin the versions
1. improve output on the commandline
2. show failures when they happen instead of at the end
3. add xdist to run tests in parallel with -n 4 for example
=> Add pytest plugins

CHANGELOG.md, src/inmanta/protocol.py, src/inmanta/server/protocol.py
=> Remove unversioned version of the API

inmanta.spec
/opt/inmanta/bin/python3 and /opt/inmanta/bin/python are now symlinks.
=> Permanent solutiont to prevent conflicting build-id symlinks.

src/inmanta/protocol/endpoints.py
This change belongs under windows support in changelog, so no entry.
=> Change generator type to prevent windows loading error

src/inmanta/env.py
Windows venv places executables such as python.exe in Scripts instead of
bin
=> This branch fixes env on windows

CHANGELOG.md, src/inmanta/config.py, tests/test_jwt.py
This patch uses python urlopen and adds a test case for this
=> Tornado httpclient does not work with asyncio loop for fetching jwks public keys

src/inmanta/data.py, tests/test_data.py
This bug is responsible for the fact that the error message "The environment id does not exist" shows up in the agents tab of the dashboard when a project has been deleted before.
=> Make sure that the deletion of a project is properly cascaded

src/inmanta/protocol/endpoints.py, tests/test_protocol.py
=> Assert that argument is an integer

CHANGELOG.md, MANIFEST.in, setup.py
This bumps version the to be release Inmanta 2019.1 and bumpd the python
version to 3.6 The code already required this version.
=> Bump version, exclude doc build and raise python

CHANGELOG.md, src/inmanta/data.py, src/inmanta/server/server.py, tests/test_server_agent.py
=> made empty deployments go to deployed state upon release.

docs/language.rst
Explicitly mention that the regex, used in a typedef statement, should be a Python regex
=> Enhance documentation regarding a regex in typedef

CHANGELOG.md, src/inmanta/app.py, src/inmanta/ast/type.py, tests/conftest.py, tests/test_app.py
fixes #1045
ran black on test/test_app.py
=> ensured error reporting is the same between export en compile 

tests/test_agent_manager.py
Make test_api test case more stable by adding the sortby argument to the assert_equal_ish check.
=> Make test_api test case more stable

misc/inmanta-agent.service, misc/inmanta-server.service
Set --log-file-level option in the service files, since logs are always written to disk by default.
=> Set --log-file-level option in the service files

CHANGELOG.md, src/inmanta/protocol/common.py, src/inmanta/protocol/decorators.py, tests/inmanta_ext/testplugin/extension.py, tests/test_protocol.py
By default all methods are exposed under /api Extensions can now use
other prefixes if desired.
fixes #1185
=> Allow methods to specify the api prefix

requirements.txt, setup.py, src/inmanta/protocol/common.py, src/inmanta/protocol/decorators.py, src/inmanta/protocol/rest/__init__.py, src/inmanta/types.py, tests/test_protocol.py
Arguments and returns types can be
- Primitive types 
- A union of valid types
- Enum
- datetime
- List of primitive types or BaseModel
- Dict of str to primitive types or BaseModel
The same applies for return types. Additionally the return type can also
be a generic ReturnValue with BaseModel, List or Dict as type.
=> Add support for List and Dict types to protocol

inmanta.spec
Fixes a bug, which:
* disables the inmanta-agent service when installing the python3-inmanta-server package. 
* disables the inmanta-server service when uninstalling the python3-inmanta-agent package
=> Run the rpm scriptlets on the correct inmanta service.

docs/administrators/auth.rst
Point to the new location that explains the openid-configuratiron endpoint on keycloak
=> Fix broken link in documentation

CHANGELOG.md, docs/faq.rst, src/inmanta/execute/scheduler.py, tests/compiler/test_iterations.py
Increased iteration limit from 2k to 10k and make it overrideable with an environment variable. Fow now this is used for scale testing of the compiler and tracking its evolution over time.
=> Increased iteration limit and override with env

requirements.txt, setup.cfg, src/inmanta/profile_mem.py, src/inmanta/reporter.py, src/inmanta/server/config.py, tests/agent_server/test_facts.py, tests/compiler/test_exception.py, tests/compiler/test_slots.py, tests/inmanta_ext/testplugin/__init__.py, tests/inmanta_ext/testplugin/extension.py, tests/server/test_compilerservice.py, tests/test_config.py, tests/test_extension_loading.py, tests/test_influxdbreporting.py, tests_common/setup.py, tox.ini
This change checks that each *.py file contains a "Copyright YYYY AUTHOR" line, with AUHTOR in this case Inmanta
=> Make pep8 angry when copyright headers are missing

src/inmanta/server/agentmanager.py, src/inmanta/server/bootloader.py, src/inmanta/server/config.py, src/inmanta/server/server.py, src/inmanta_ext/core/extension.py, tests/test_app.py, tests/test_extension_loading.py
This commit adds a config setting to enable extensions. They are no longer loaded by default. This commit also cleans up core vs other slices.
Fixes #1170
=> Add option to enable extensions

CHANGELOG.md, src/inmanta/export.py, src/inmanta/server/compilerservice.py, tests/server/test_compilerservice.py, tests/test_export.py
- A valid project for the compiler service is now one with a project.yml and not a .git
- When a compile is successful but there are no resources, a version is still created.
=> Fixes in export and compiler behaviour

requirements.txt
Execnet version 1.7.0 contains a bug. Due to this bug, the source code of the module to be executed is not serialized. An issue exists on the GitHub repo of execnet to resolve this problem (https://github.com/pytest-dev/execnet/issues/108). For the time being the only solution is to downgrade to version 1.6.1
=> Rollback version execnet

src/inmanta/server/compilerservice.py, src/inmanta/server/server.py, tests/server/test_compilerservice.py
Make sure that environment variable set on the Inmanta server are forwarded to the subprocess that executes the compilation.
=> Forward env vars server to compilerservice. 

docs/administrators/metering.rst
This reverts commit 83ff696f72ab46f69feb79abb6d72d1c0a493151.
https://github.com/dropwizard/metrics/issues/1484
=> Revert "replaced link to dropwizard metrics, which is offline (#1397)"

requirements.txt
When starting from a clean environment, running `make install` and then `make mypy` results in an error, reporting that lxml is not installed. Running `pip install lxml` manually resolves this. Should lxml be added to the requirements.txt file?
=> added missing dependency to requirements.txt: lxml

src/inmanta/data/model.py
Openstack handler reports an attribute as list of strings. This is also valid. This change only defines it one level deep. The definition could also be recursive. @wouterdb @sanderr could you make a suggestion here?
=> Define the types a bit less strict

Makefile, tox.ini
This should print debug logs when a test fails instead of only warning
=> Enable debug logging for tests

src/inmanta/agent/agent.py
Fix a performance regression where a list with many doubles caused a serious performance regression. This fix makes sure that ensure_code never executes any doubles.
=> Fix performance regression

src/inmanta/data/schema.py, tests/db/test_db_schema.py
Print all migrations with schema name in logger
fixes #1478
=> Create child logger with schema name

docs/language.rst
The documentation shows string interpolation using triple quotes (`"""{{string}} interpolation"""`) while the compiler only seems to interpolate in single-quoted strings (`"{{string}} interpolation"`). Example model:
```
entity File:
string path
end
implement File using std::none
for file in files:
std::print("""/backup{{file.path}}""")
end
files =
[ File(path = "/file")
, File(path = "/otherfile")
]
```
=> fixed string interpolation documentation

CHANGELOG.md, src/inmanta/parser/plyInmantaLex.py, tests/test_parser.py
Arnaud noticed that a string ending with an escaped backslash (`'\\'`) was not allowed. This commit fixes the issue.
An possible alternative to the regex in this commit, closer to the original would be this: `r"(\"((\\\\)+|.*?[^\\](\\\\)*)\")|(\'((\\\\)+|.*?[^\\](\\\\)*)\')"` but it seems less readable.
=> Lexer string regex

setup.cfg
This adds quite strict checking to pydantic
docs: https://pydantic-docs.helpmanual.io/mypy_plugin/#plugin-settings
it finds the following problems
```
+ src/inmanta/data/__init__.py:714: error: Argument "default" to "EnvironmentSetting" has incompatible type "Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]], None]"; expected "Union[StrictNonIntBool, int, str, Dict[str, Union[str, int, StrictNonIntBool]]]"
+ src/inmanta/data/__init__.py:715: error: Argument "doc" to "EnvironmentSetting" has incompatible type "Optional[str]"; expected "str"
+ src/inmanta/agent/agent.py:266: error: Argument "status" to "Event" has incompatible type "Optional[ResourceState]"; expected "ResourceState"
+ src/inmanta/agent/agent.py:266: error: Argument "change" to "Event" has …
```
=> added mypy pydantic support

src/inmanta/server/agentmanager.py, tests/test_server.py
Related to #1098 
It seems that the wait_for_exit waits for the timeout when the process has already ended.
This affects the runtime of tests/test_server.py::test_autostart and tests/test_server.py::test_autostart_batched for example (locally it reduced the total runtime by ~30 sec)
=> Don't wait for already terminated processes

tests/agent_server/test_server_agent.py, tests/test_app.py, tests/test_server.py, tox.ini
Closes #1098 
The rest of the slower test cases generally:
- Test complex flows (and possibly could be split to several test cases, but that wouldn't speed up the process)
- Have slow / complex test setups
- Test a slower/bigger part of the system under test
- Test timeouts explicitly
- Or more of the above combined
I haven't found a common pattern, that could be improved and affects a substantial portion of the test cases.
=> Reduce timeouts on test cases

docs/Makefile, docs/conf.py
sphinx-contrib/redoc only supports html as a build target
=> Only include redoc in html doc builds

docs/conf.py
The inmanta-docs job checks the conf.py for the release version, that way the tags are not defined like when sphinx processes it.
=> Handle undefined tags in docs

src/inmanta/agent/io/local.py
In docker containers certain sudo operations are not allowed. This produces an error on stderr but the result is still valid:
stdout: b'a94a8fe5ccb19ba61c4c0873d391e987982fbbd3  /tmp/tmp82pla41d/hashfile\n', 
stderr: b'sudo: setrlimit(RLIMIT_CORE): Operation not permitted\n'
This PR validates the output in stdout instead of assuming if something is in stderr the result is wrong.
=> Fix file hash when having errors in sha1sum output

src/inmanta/protocol/rest/server.py, tests/test_cli.py
The Tornado AsyncHttpClient uses HTTP/1.1, added a test case to verify that
Closes #1740
=> Verify that inmanta-cli uses HTTP/1.1

CHANGELOG.md, src/inmanta/data/schema.py, tests/db/test_db_schema.py
Downgrading the database schema version is not supported, this change introduces a check to fail if that would be required.
closes #1878
=> Fail if db schema downgrade is required

CHANGELOG.md, src/inmanta/data/schema.py, tests/data/db_with_invalid_versions/invalid_versions/V2.py, tests/data/db_with_invalid_versions/invalid_versions/v1b.py, tests/data/db_with_invalid_versions/invalid_versions/ver1.py, tests/data/db_with_invalid_versions/invalid_versions/ver1a.py, tests/data/db_with_invalid_versions/invalid_versions/version3.py, tests/db/test_db_schema.py
Log warning if a database migration script's name doesn't conform to `v<version_number>.py`
closes #1912
=> Log warning on invalid db update script name

src/inmanta/ast/constraint/expression.py, src/inmanta/ast/statements/__init__.py, src/inmanta/ast/statements/assign.py, src/inmanta/ast/statements/call.py, tests/compiler/dataflow/test_model_assignment.py, tests/compiler/dataflow/test_model_stubs.py
Moved NodeStub creation from ExpressionStatement to unsupported children. `ExpressionStatement.get_dataflow_node()` now raises `NotImplementedError`, as it should.
closes #1869
=> dataflow: moved NodeStub creation from ExpressionStatement to unsupported children: fixes #1869

src/inmanta/ast/attribute.py, src/inmanta/execute/runtime.py, tests/compiler/dataflow/test_model_entities.py
Compiling with `--experimental-data-trace` failed when the model included a child entity that redeclared an existing attribute, for example for specifying a default value. This pull request fixes that.
closes #1974
=> fixed dataflow compilation failure for entity extension: fixes #1974

CHANGELOG.md, src/inmanta/server/services/resourceservice.py, tests/test_server.py
Adds timestamps to the log lines of the resource action log, by specifying a log formatter.
closes #1496 
=> Add timestamp to resource action log

CHANGELOG.md, src/inmanta/ast/statements/define.py, src/inmanta/parser/plyInmantaParser.py, tests/compiler/test_implement.py, tests/test_parser.py
Allows specifying parents implementations in list with other implementations (`implement A using parents, some_impl`).
closes #1971
=> allow parents in implementation list: fixes #1971

src/inmanta/ast/statements/define.py, tests/compiler/test_basics.py
Fixes the bug that breaks lsm and compilerscaling tests 
=> fix for regression in implements statement

CHANGELOG.md, docs/model_developers/modules.rst, src/inmanta/moduletool.py, tests/moduletool/common.py, tests/moduletool/test_module_tool_basics.py
=> Add no-tag option to moduletool commit

src/inmanta/execute/runtime.py, tests/compiler/test_warnings.py
Fixes wrongfully raised deprecation warning when using nullable attributes in presence of diamond inheritance.
As a side effect prevents creation of multiple `ResultVariable` instances when an attribute occurs multiple times in the inheritance hierarchy.
closes #1950
=> fixed nullable attribute deprecation warning in entity with diamond inheritance: fixes #1950

docs/language.rst
Updates documentation after allowing parents in normal implementation list (#1971)
closes #1986
=> updated documentation related to implementation selection with parents: fixes #1986

src/inmanta/execute/dataflow/__init__.py, src/inmanta/execute/runtime.py, tests/compiler/dataflow/conftest.py, tests/compiler/dataflow/test_assignment.py, tests/compiler/dataflow/test_basic.py, tests/compiler/dataflow/test_dataflow_entities.py, tests/compiler/dataflow/test_leaves.py, tests/compiler/dataflow/test_model_assignment.py, tests/compiler/dataflow/test_model_dynamic_scope.py, tests/compiler/dataflow/test_model_root_cause.py, tests/compiler/dataflow/test_model_stubs.py
Fixes the duplicate lookup between `ResultVariables` and `AssignableNodeReferences`
closes #1879
=> dataflow duplicate lookup: fixes #1879

CHANGELOG.md, src/inmanta/protocol/openapi/converter.py, src/inmanta/protocol/openapi/model.py, tests/test_openapi.py
Adds tags based on the slice
closes #1751 
=> Add tags to openapi definition

src/inmanta/protocol/openapi/converter.py
The function to get the correct version wasn't called in the previous PR.
closes #1994 
=> Apply missing get_version call to api docs

src/inmanta/parser/plyInmantaParser.py
Fixes `WARNING: Symbol 'ns_list' is unreachable` since `ns_list` has been replaced by `implement_ns_list`.
~~closes *Add ticket reference here*~~
=> fixed parser warning ns_list unreachable

CHANGELOG.md, src/inmanta/ast/statements/generator.py, tests/compiler/test_dict.py
Fixed double assignment error resulting from combining constructor kwargs with default values
closes #2003
=> fixed constructor defaults and kwargs issue: fixes #2003

CHANGELOG.md, src/inmanta/execute/proxy.py, tests/test_proxy.py
Fixes the recursive unwrapping of dicts using `DynamicProxy.unwrap()`.
closes #2004
=> fixed recusive unwrapping of dict return values from plugins: fixes #2004

CHANGELOG.md, src/inmanta/parser/__init__.py, src/inmanta/parser/plyInmantaParser.py, tests/test_parser.py
Deprecated the old relation definition syntax.
closes #2000
=> deprecated old relation syntax: fixes #2000

CHANGELOG.md, src/inmanta/server/services/environmentservice.py, tests/test_project.py
To allow other server slices to get notified about events concerning environments.
closes #1996 
=> Add event listener to environment service

CHANGELOG.md, src/inmanta/ast/type.py, src/inmanta/export.py, tests/test_type.py
`Type.type_string()` is now defined as returning the representation of the type in the inmanta DSL.
closes inmanta/lsm#75
related to inmanta/lsm#82
=> updated inmanta.ast.Type.type_string() to return the DSL type representation

src/inmanta/ast/attribute.py, tests/test_type.py
`Attribute.validate` now takes multi and nullable into account.
closes #2031
=> updated Attribute.validate to take multi and nullable into account

src/inmanta/agent/config.py
Clarify that setting the agent-deploy-interval to zero disables the timer.
=> Add clarification for agent-deploy-interval setting

tests/test_compilation.py
Remove the downloaded std module after the test.
closes #2026 
~Changelog entry~
- ~[ ] End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )~
=> Cleanup after compile_138 test

CHANGELOG.md, src/inmanta/ast/statements/define.py, tests/compiler/test_warnings.py
Adds warning for typedefs where name == built-in type name
closes #2030
=> added warning when overwriting built-in type

docs/glossary.rst
A typo lead to a broken link
closes #2017 
- ~[ ] Changelog entry~
=> Fix broken link in docs

CHANGELOG.md, docs/conf.py, docs/reference/commands.rst, requirements.txt
With https://sphinx-click.readthedocs.io/en/latest/
closes #1992 
=> Include inmanta-cli docs in sphinx docs

docs/reference/config-namespaces/core.conf, docs/reference/config.rst
Store the namespaces that contain the `Option()` definitions in a separate file.
=> Use the namespace-files option in the show-options directive

tests/test_agent_manager.py
Set the loglevel of the `test_restart_on_environment_setting()` testcase to DEBUG, since the test case requires it.
=> Set required loglevel for test case.

CHANGELOG.md, src/inmanta/data/__init__.py, src/inmanta/server/config.py, src/inmanta/server/protocol.py, src/inmanta/server/services/compilerservice.py, tests/server/test_compilerservice.py
Cleans up old compiler reports periodically
closes #2054 
=> Clean up old compile reports

setup.py
The typing library has become part of the standard python library since python 3.5
Importing it in higher versions should not cause problems, but it does: https://github.com/python/typing/issues/573
As we only support 3.6 and up, it can be safely removed.
=> removed dependency on typing

requirements.txt, tests_common/setup.py
removed typing from requirements.txt as it is a built-in for all supported python versions and breaks pip
see python/typing#573
=> removed typing from requirements.txt

CHANGELOG.md, src/inmanta/protocol/common.py, src/inmanta/protocol/rest/client.py, src/inmanta/protocol/rest/server.py, tests/test_protocol.py
REST endpoint return value didn't get decoded if content type was html with utf-8 charset. This caused a test to fail in some instances because it expected a `str` but got a `bytes` object instead.
closes #2074
=> fixed rest endpoint return value decoding for html with charset

CHANGELOG.md, src/inmanta/agent/handler.py, tests/test_handler.py
added resource name to log lines in agent log
quick fix, no issue attached
- [] ~~End user documentation is included or an issue is created for end-user documentation (add ref to issue here: )~~
=> added resource name to log lines in agent log

CHANGELOG.md, src/inmanta/config.py, tests/test_config.py
fixed empty config list being read as list of empty string
#2097
=> fixed empty config list being read as list of empty string

CHANGELOG.md, src/inmanta/protocol/endpoints.py, src/inmanta/protocol/methods.py, src/inmanta/server/protocol.py, tests/test_2way_protocol.py
added test cases for session events on agent
also discovered that re-connection is delayed with one
longpoll interval if the agent considered the session expired,
but the server doesn't.
This potentially rare, so perhaps we should not specially handle this.
- [] ~~Attached issue to pull request~~
=> added test cases for session events on agent

CHANGELOG.md, src/inmanta/module.py
removed warning about collecting requirements for project that has not been loaded completely on initial compile
closes #2125
- ~~[x] Type annotations are present~~
- ~~[x] Code is clear and sufficiently documented~~
- ~~[x] No (preventable) type errors (check using make mypy or make mypy-diff)~~
- ~~[x] Sufficient test cases (reproduces the bug/tests the requested feature)~~
- ~~[x] Correct, in line with design~~
- ~~[x] End user documentation is included or an issue is created for end-user documentation~~
=> removed unneeded warning (#2125)

requirements.txt
Pin the inmanta-sphinx dependency. This is required to make the documentation builds of releases repeatable.
=> Pin inmanta-sphinx dependency

CHANGELOG.md, requirements.txt, src/inmanta/data/__init__.py, src/inmanta/db/versions/v5.py, src/inmanta/server/services/compilerservice.py, tests/conftest.py, tests/server/test_compilerservice.py
Remedies the filling of the compile queue with a lot of very similar compiles by merging them into one.
closes #2137
=> added merging of compiles when added to compile queue

CHANGELOG.md, src/inmanta/compiler/__init__.py
Restore support to pass mocking information to the compiler.
=> Restore support to pass mocking information to the compiler

CHANGELOG.md, docs/language.rst
Added documentation on how a string is matched against a regex defined in a regex-based typedef.
closes #2214 
=> Added documentation on regex matching in regex-based typedefs

CHANGELOG.md, requirements.txt, setup.cfg, src/inmanta/ast/type.py, tests/compiler/test_typing.py, tests/test_type.py
Allow equality checks between types to support optional value overrides
closes #2243
=> added __eq__ methods to types

CHANGELOG.md, src/inmanta/protocol/common.py, tests/test_protocol.py
=> Don't add path params as query params to the url in the client

CHANGELOG.md, src/inmanta/ast/__init__.py, tests/compiler/test_compile_export.py, tests/compiler/test_exception.py, tests/compiler/test_plugins.py, tests/conftest.py, tests/data/modules/tests/plugins/__init__.py
Modified the ExplicitPluginException to
1. report the PluginException that caused to to the compiler json output instead of itself
2. when printing the stack trace, also report the error message of the PluginException
closes #2304
```bash
inmanta compile --export-compile-data 
PluginException in plugin find_subnet_for (reported in find_subnet_for(self.ip_address,self.host.**.subnets) (**/full_service_model.cf:63))
caused by:
Could not find a subnet for ip 192.168.100.10
inmanta_plugins.**.NoSubnetFoundForIp: 192.168.100.10
```
```json
{
"errors": [
{
"category": "plugin_exception",
"type": "inmanta_plugins.**.NoSubnetFoundForIp",
"message": "Could not find a subnet for ip 192.168.100.10",
"location": {
"uri": "**/model/full_service_model.cf",
"range": {
"start": {
"line": 62,
"character": …
```
=> improved reporting of PluginExceptions

CHANGELOG.md, src/inmanta/loader.py, tests/test_loader.py
backwards compatibility patch for agent plugin source loading
closes #2312
=> backwards compatibility patch for agent plugin source loading

src/inmanta/loader.py, tests/test_loader.py
Ensure that sources in the code directory of an agent are ignored when they are formatted using the pre Inmanta 2020.4 on disk format.
Bugfix on #2162
=> Issue/ignore pre2020.4 source files

CHANGELOG.md, src/inmanta/server/services/compilerservice.py, tests/server/test_compilerservice.py
Fix issue where "compile_data_json_file" is referenced before assignment.
closes #2361 
=> Fix 'compile_data_json_file' referenced before assignment

CHANGELOG.md, src/inmanta/const.py, src/inmanta/protocol/methods_v2.py, src/inmanta/server/server.py
=> Add ApiDocsFormat enum for Openapi docs endpoint

CHANGELOG.md, src/inmanta/execute/runtime.py, src/inmanta/execute/scheduler.py, tests/compiler/test_execution.py
When a plugin takes a higher multiplicity relation (a) as input, that gets its content from another higher multiplicity relation (b), the compiler gets stuck. The plugin waits for the relation a. The ListVariable for the relation a has progress potential (something that doesn't support gradual execution needs the value) and one promise (from the assignment from list b). List b has no progress potential (all things that listen to it support gradual execution) and no promisses .
Compiler will not freeze a because it has a promisse, and will not freeze b because is has no progress potential.
closes #2378
=> fixed #2378 Compiler Scheduling

CHANGELOG.md, src/inmanta/data/__init__.py, src/inmanta/protocol/methods.py, src/inmanta/protocol/methods_v2.py, src/inmanta/server/services/environmentservice.py, tests/server/test_env_settings.py
=> Ensure that a protected environment can't be decommissioned

requirements.txt
Pytest-postgresql sets the locale of the in the pg_ctl command to C.UTF-8 by default in version 2.5.1. (See: https://github.com/ClearcodeHQ/pytest-postgresql/commit/ff31a3f38bb92f7c92325db9f67941327849aa4f and https://github.com/ClearcodeHQ/pytest-postgresql/commit/7427378161a3d6dbb7953e258f9ef2732d8a0809). This breaks the tests on centos7, since centos7 doesn't support C.UTF-8 locale. 
Or should we open a ticket at pytest-postgresql for this?
=> Revert pytest-postgresql to 2.5.0

CHANGELOG.md, src/inmanta/env.py, tests/test_env.py
adds support for environment markers as described in PEP 508
closes #2359
=> added support for environment markers as described in PEP 508

src/inmanta/data/__init__.py, src/inmanta/db/versions/v7.py, src/inmanta/protocol/methods.py, src/inmanta/protocol/methods_v2.py, src/inmanta/server/services/compilerservice.py, src/inmanta/server/services/orchestrationservice.py, src/inmanta/server/services/resourceservice.py, tests/server/test_compilerservice.py, tests/test_data.py
- optimized the get_version method to consume less resources
- added an upper limit of 1000 items per page on all API endpoints with paging
closes #2432
(red is good)
```diff
+ src/inmanta/data/__init__.py:1861: error: "ResourceAction" gets multiple values for keyword argument "from_postgres"
- src/inmanta/server/services/resourceservice.py:588: error: Argument "limit" to "query_resource_actions" of "ResourceAction" has incompatible type "Optional[int]"; expected "int"
- src/inmanta/server/services/orchestrationservice.py:106: error: Argument 3 to "get_versions" of "ConfigurationModel" has incompatible type "Optional[int]"; expected "int"
- src/inmanta/server/services/orchestrationservice.py:112: error: …
```
=> Protect server against large API results

CHANGELOG.md, src/inmanta/execute/proxy.py, tests/conftest.py, tests/data/modules/exp/model/_init.cf, tests/test_export.py
Added support for null in dict in exporter
fixes #2437
=> added support for null in dict in exporter

src/inmanta/execute/proxy.py, tox.ini
Running the test suite multiple times with python 3.8 hasn't uncovered any issues (apart from a deprecation warning that this fix is for).
The tests pass on Ubuntu, Centos8, Fedora31, as well as on the Jenkins test executors.
closes #2219 
=> Fix Python3.8 deprecation warning

CHANGELOG.md, src/inmanta/ast/statements/call.py, tests/test_compiler_entrypoints.py
added plugin call anchor to support ctrl-click on plugin calls
closes #1954
=> added plugin call anchor

CHANGELOG.md, src/inmanta/parser/plyInmantaParser.py, tests/compiler/test_conditional.py, tests/compiler/test_defaults.py, tests/compiler/test_define.py, tests/compiler/test_exception.py, tests/compiler/test_execution.py, tests/compiler/test_list.py, tests/compiler/test_null.py, tests/compiler/test_typedef.py, tests/compiler/test_typing.py
This PR makes `Attribute` location a `Range` instead of a plain `Location`. This is related to #2481 though while working on this I realized the handling of plain `Location` instances can be improved on the vscode side as well. Now I'm not sure this PR should even be merged. The question is what we want the `Attribute`'s location to represent:
- just a line number, as it is now (don't merge this PR (or change it a bit, there's an inconsistency in the tokens used for the location of dicts and other attributes respectively))
- the range of the type declaration
- the range of the attribute name (current status of this PR)
- the combined range of the type declaration and the attribute name (without leading whitespace)
@wouterdb @arnaudsjs wdyt? I'm slightly in favor of leaving this as is …
=> made attribute location a range

src/inmanta/plugins.py, tests/compiler/test_plugins.py
I couldn't find a simple way to cleanly and reliably determine the correct `Range` for a plugin definition. This PR sets `Plugin.location` to a `Location` instance instead of the current (inaccurate) `Range` instance. Related to #2482
=> use Location instead of Range for Plugin.location

.github/dependabot.yml, requirements.txt
Downgrade the sphinx dependency to version 3.2.1, because version 3.3.0 breaks the link check on the documentation (See: https://github.com/inmanta/inmanta/issues/2495).
=> Downgrade sphinx dependency

.github/dependabot.yml, requirements.txt
Bumping pytest-postgresql version to 2.5.2.
closes #2494 
=> Bumping pytest-postgresql version to 2.5.2

CHANGELOG.md, inmanta.spec
Add support to build RPMs for a different python version.
closes #1857
=> Add support to build RPM for a different python version.

CHANGELOG.md, src/inmanta/app.py, tests/test_app_cli.py, tests/test_cli.py
Fixes the bug that made `inmanta export` fail when `--server_address` was set.
closes #2514 
=> Fixing option checking

misc/inmanta.vim
- added `null`, `self`, `TODO`
- restructured Statement minor groups to be more specific according to vim syntax naming conventions (http://vimdoc.sourceforge.net/htmldoc/syntax.html or `:help syntax` in vim)
=> extended vim syntax highlighting

CHANGELOG.md, src/inmanta/agent/agent.py, tests/agent_server/conftest.py, tests/agent_server/test_send_events.py
Handle failure in an event handler consistently for local and non-local agents.
closes #2509
=> Handle failure in an event handler consistently

CHANGELOG.md, src/inmanta/agent/handler.py, tests/agent_server/conftest.py, tests/agent_server/test_resource_handler.py
=> Handle JSON serialization errors in handler log messages

requirements.txt
The new pip dependency resolver is more strict, importlib-metadata has a conflict:
Tox requires importlib-metadata version <3, while requirements.txt has 3.1
=> Downgrade importlib-metadata dependency

requirements.txt
requirements.txt is used as a constraint file for some jobs in irt.
The issue is that it has a dependency, that has extras, and that's not allowed for constraints with the new pip resolver
=> Fix for dependencies with extras used as constraints

CHANGELOG.md, src/inmanta/agent/handler.py, src/inmanta/data/model.py, tests/test_agent.py
fixed too restrictive typing (and coercing) of AttributeStateChange
closes #2540
=> fixed too restrictive typing (and coercing) of AttributeStateChange

docs/check_sphinx.py, requirements.txt, tox.ini
adds a seperate test that builds the docs and checks the returncode.
Using a mark only the build test can be called.
Replaced the original tox doc build test to call this.
Add an env to tox that performs both the build and linkcheck.
Should I add an entry to teh changelog?
Needed for https://github.com/inmanta/infra-tickets/issues/111
after this passed review, a nightly build needs to be configured to run the link-check
=> Split docs build and link check

tox.ini
Adds the tox docs build to the default tox targets.
As described in https://github.com/inmanta/infra-tickets/issues/111
=> Add docs to tox targets

docs/conf.py
This sets the year always to the current year because we forget to bump it.
Not sure if a changelog entry is required for this.
=> Use the current year for the copyright year

requirements.txt
This reverts commit 54fd354856bc3de1cdddc8d9aa1f2335d9614ef5.
The new cryptography version breaks the rpm build. Until #2518 is resolved, we should use the previous version.
=> Revert "Bump cryptography from 3.2.1 to 3.3 (#2560)"

CHANGELOG.md, docs/model_developers/configurationmodel.rst, docs/reference/projectyml.rst
We discovered that the documentation of install mode is not in line with the actual behavior, this should correct the documentation
=> attempt to correct the install_model documentation

tox.ini
A transitive dependency (chardet) gets a conflicting version, when the requirements are installed with the default (old) pip version with tox (9.0.3).
Newer pip versions handle this conflict correctly
=> Installing with tox should use the latest pip version

requirements.txt, tox.ini
- tox-venv has been deprecated (https://github.com/tox-dev/tox-venv), since virtualenv now creates venv style environments.
- virtualenv installs the latest pip by default
=> Remove outdated tox-venv dependency

requirements.txt
Reverts inmanta/inmanta#2566
I had a typo in the original comment to dependabot to ignore this, so it was merged again
=> Revert "Bump cryptography from 3.2.1 to 3.3"

.bumpversion.cfg
I don't think it makes sense to continue having such a complicated `.bumpversion.cfg` file
=> simplified .bumpversion.cfg now that we're doing semantic versioning

tests_common/setup.py
This file appears to have been forgotten when renaming and switching to semantic versioning. This is blocking the release.
=> set correct version for tests_common

.bumpversion.cfg
Explicitly added files to bumpversion file. This will need to be cherry-picked to `iso3` and `iso4`.
part of inmanta/irt#393
=> explicitly added files to bumpversion file

.bumpversion.cfg, tests_common/setup.py
Part of inmanta/irt#393.
I think `tests_common/setup.py` was forgotten in #2607.
=> explicitly added files to bumpversion file (#2635)

requirements.txt
We released with a broken pytest-postgresql for centos7. This bump seems to fix it when I run the tests locally in docker on my machine. It does not affect customer code, so should not be released. Just on sitting on the latest branch is enough.
closes #2629 
=> Bump dep on latest branch to fix pytest docker builds

CHANGELOG.md, Makefile, src/inmanta/data/__init__.py, tests/test_data.py
- It is not supported to use parameters in order by. This patch fixes this.
- Add some typing in related methods while reading code
- Use string formatters to improve code readbility
- Fix a warning in make format
- Added a test case for input validation
I did not add an extra test case to validate the order because test_data.py::test_get_latest_resource
was broken. This patch fixes it.
closes #2638 
=> Fix order by that does not support parameters

CHANGELOG.md, src/inmanta/env.py, tests/test_env.py
Improve handling of python path for processes that are forked by the server/compiler/agent. This should fix issues where the compiler or agents needs to install python packages that are already present in the server python path / venv.
closes #2650 
=> Fix python path inheritance for virtual envs

CHANGELOG.md, src/inmanta/env.py, tests/test_env.py
- Upgrade pip when venv is created
- Fix a potential error in pip install
Should we add pip >= 21.0.1 to the requirements file?
The tests run fine on my machine but seem to be unstable on jenkins. The tests also become a lot slower. So what do we do about it? The current irt moduleset issues seem to be related to not having a pip that can install cryptography (which might be fixable with doing correct PYTHONPATH inheritance)
=> Upgrade pip

requirements.txt, tests/test_env.py
The env tests did not support python3.8 yet. This fixes this.
=> Fix test on python38

requirements.txt
The version bumps for cryptography were disabled in the past due to failing tests. By bumping it manually, dependabot will start bumping it again.
=> Re-enable version bumps cryptography dependency

docs/conf.py, tox.ini
Change environment variable `INMANTA_RUNNING_TESTS` to `INMANTA_DONT_DISCOVER_VERSION`. This was done, because the use of this environment variable is not limited to running test cases.
=> Rename environment variable INMANTA_RUNNING_TESTS

requirements.dev.txt
Use core instead of extension feature in inmanta-dev-dependencies.
=> Use core instead of extension feature in inmanta-dev-dependencies

tests/conftest.py, tests/server/test_compilerservice.py, tox.ini
* Fix a race condition in the tests where a compile request is retrieved from the queue, while it's not yet added to the compile queue.
* Remove code duplication.
=> Fix race condition in tests

.github/dependabot.yml
Disable version bumps larger or equal than `0.3.0` for the `openapi-spec-validator` dependency until #2729 is resolved.
=> Disable version bumps for the openapi-spec-validator dependency

requirements.txt
Ensure that the pinned version of pip is compatible with the cryptography dependency.
=> Bump pip to 21.0.1

pyproject.toml
I'll cherry-pick this to `iso4` and `iso5-next`.
=> old release pipeline cleanup: removed dashboard constraint from pyproject.toml

docs/Makefile
Install the `pytest-inmanta-extensions` via the `requirements.dev.txt` file as such that version constraints are taken into account.
=> Install openapi dependencies from constraint file

pyproject.toml
I'm not 100% sure of this but I think this needs to be bumped. This PR bumps it to the last stable version (the current dev version doesn't have any changes except for the `pyproject.toml` file).
I'm planning to cherry-pick this to `iso3-next`.
=> Iso3 dashboard pin

CHANGELOG.md, src/inmanta/agent/io/local.py, tests/conftest.py
This PR adds the following fixes:
* Ensure not KeyError occurs when `io.run()` is called while the `PYTHONPATH` environment variable is not present in `os.environ`.
* Ensure the `PYTHONPATH` environment variable is correctly restored in the `deactive_venv` fixture.
closes #2747
=> Prevent KeyError on PYTHONPATH

changelogs/unreleased/fix-race-agent-timeout-test-case.yml, tests/test_2way_protocol.py
Fix race condition in `test_agent_timeout` test case.
=> Fix race condition in `test_agent_timeout` test case.

changelogs/unreleased/pytest-inmanta-pin-core.yml, tests_common/setup.py
Not 100% sure about this one but I believe this should pin with ~=, same as iso4.
I'll cherry-pick to iso5-next if approved. After cherry-picking I'll rebuild `pytest-inmanta-extensions` and retrigger the specific module sets build to make sure it still works with this new constraint.
=> pin core dependency with ~= instead of >= for pytest-inmanta-extensions

.github/dependabot.yml
Re-enable pip updates 
closes #2894
:warning: I didn't add a changelog entry as this only goes into master, is that OK? 
=> re-enable pip updates

changelogs/5.1.0/417-add-changelog-to-docs.yml
This change was reverted on iso3, see cb90b27dcea2b602900811aafbfacf1845f7779d.
=> fixed change entry after reverting commit on iso3

changelogs/5.1.0/2787-compiler-memory-leak.yml, changelogs/unreleased/2683-port-pyjwt2.yml, changelogs/unreleased/fix-change-entries.yml
Start from a clean slate for some change entries that were forgotten and merged at a later point. This messes with the timestamp-reasoning of the change entry check.
=> fixed change entries

.github/dependabot.yml
In order to make life of the buildmaster a bit easier and to ease us along to switching to iso5, I start with the rollout of long delayed rollout of https://github.com/inmanta/irt/issues/512
This is a first cautious step, enabling dependency updates on iso4.
=> enable dependabot on iso4

changelogs/unreleased/3565-compatibility-iso4-modulev2.yml
#3638 contained a bugfix note in the change entry that I believe is not in its place here. The new project metadata format has not yet been released so there is no bug. I only noticed when the `merge-tool-ready` label had already been added.
Will be merged manually.
=> removed bugfix note from change entry

requirements.dev.txt
The OSS stable docs build failed because of a dependency conflict between the pinned requirements and the version of black pinned in `inmanta-dev-dependencies`. This PR should fix that. I have just released a new version of `inmanta-dev-dependencies`, which is used here.
I will fast-forward to appropriate branches.
=> bump inmanta-dev-dependencies for docs build

changelogs/unreleased/unstable-test-psutil.yml, tests/agent_server/test_server_agent.py
**Cherry pick this change onto the stable branch to fix broken tests.**
We are getting regular failures in the nightly builds due to this.
This is a first attempt to get to the bottom of it.
=> Handle psutil exceptions when processes are gone (PR #4315)

src/inmanta/parser/plyInmantaParser.py
Made an attempt to simplify precedence reasoning and to make it more consistent.
- Got rid of most custom precedence levels
- Replaced them with a single `LOW` precedence level that tries to shift tokens eagerly
- Added documentation for the `empty` token to include its two primary use cases
- Use the `empty` rule everywhere custom precedence was currently used. This is the part I'm least certain about. I feel like it helps readability because
1. the comment for the `empty` token is now clear on its uses
2. when used for precedence enforcement it always occurs in a place where the preceding token appears in a similar context in another rule, followed by something non-empty
- Added a missing precedence rule for the `MATCHING` terminal token
A lot of this is very subjective so I'd …
=> refactored precedence rules

tests/agent_server/deploy/test_scheduler_agent.py
Adds a test helper class for scheduler testing. `ManagedExecutor` expects to be driven by the test case itself. It hangs at the start of deploy on a future for which the result should be set by the test case. You can find usage examples in #8131.
=> added ManagedExecutor test helper

.github/dependabot.yml, requirements.txt
Hold back pydantic-core because of pydantic/pydantic#10494.
Does not affect inmanta-core directly, but it does inmanta-lsm (inmanta/inmanta-lsm#1912) so we need to make sure the core requirements file is in line for the iso RPM build.
part of inmanta/inmanta-lsm#1900
=> hold back pydantic-core

changelogs/unreleased/track-resources-that-skipped-deployment.yml, src/inmanta/deploy/state.py, src/inmanta/deploy/tasks.py, tests/deploy/e2e/test_deploy.py, tests/deploy/test_scheduler_agent.py
In the current implementation we don't track skipped resources, and simply label them as failed. This PR changes that. In the future we will have a different state for resources that were skipped by a custom handler
=> Track skipped resources

requirements.txt
Downgrade the psutil pin (applied yesterday) because it is not compatible with inmanta-license.
=> downgrade psutil pin

tests/conftest.py
Iso7: dropped the deprecated event loop fixture from `conftest`, which is used by `pytest-inmanta-extensions`.
=> drop event loop fixture

src/inmanta/references.py, tests/data/modules_v2/refs/inmanta_plugins/refs/__init__.py, tests/data/modules_v2/refs/inmanta_plugins/refs/dc.py, tests/test_references.py
Some part of the code use string conversion instead of the repr
=> revert __str__ guard for references
