inmanta/inmanta-core

- src/inmanta/ast/statements/generator.py
- tests/test_compilation.py
> fixed lexical scoping of implements statement.

- src/inmanta/module.py
- src/inmanta/util.py
- tests/test_moduletool.py
compiler version is checked when updating or installing modules
fixes #158
> Added option compiler_version to modules.yaml

- src/inmanta/module.py
use to install dev versions of modules
fixes #159
> added option install_mode to project.yml

- src/inmanta/module.py
env was no longer correctly passed on to checkout/clone/update sub process
fixes #172
> fixed checkout for private repos

- src/inmanta/agent/agent.py
- tests/test_server_agent.py
> made it possible to run multiple agents per agent process

- docs/commands.rst
- docs/conf.py
- docs/docs.rst
- docs/index.rst
- docs/install.rst
- docs/language.rst
- docs/modules.rst
- docs/quickstart.rst
- Added consistency throughout the text
- Extended explanation of Inmanta
- This makes it easier to follow the quickstart.
TODO: clear distinction between the use of the CLI and the use of the dashboard
> First review of documentation

- src/inmanta/server/server.py
> fixed race condition for multiple agents in one agent process

- docs/quickstart.rst
- minor additions/clarifications
- typos
> Second review of quickstart

- src/inmanta/execute/runtime.py
- tests/test_compilation.py
> Fixed compiler corruption when a relation was set twice

- src/inmanta/module.py
- tests/test_moduletool.py
> added support for semantic versioing to module commit command

- src/inmanta/agent/cache.py
- src/inmanta/agent/handler.py
- tests/test_cache.py
> added option to caching annotation to not cache None values

- src/inmanta/ast/statements/assign.py
- tests/data/modules/tests/module.yml
- tests/data/modules/tests/plugins/__init__.py
- tests/test_compilation.py
> added support for Unknows to inline templates

- src/inmanta/data.py
- src/inmanta/protocol.py
- src/inmanta/server/agentmanager.py
- tests/test_2way_protocol.py
- tests/test_server_agent.py
added test case for server restart
fixes #233
> fix for race conditions in session handling

- src/inmanta/export.py
- src/inmanta/resources.py
- tests/test_compilation.py
> added test for cyclic dependencies

- src/inmanta/config.py
> fixed parsing of config options with spaces

- .editorconfig
> Add editorconfig editor settings

- docs/language.rst
- src/inmanta/ast/entity.py
- src/inmanta/ast/statements/define.py
- tests/test_compilation.py
> made it possible to override defaults

- src/inmanta/parser/plyInmantaParser.py
- tests/test_compiler.py
> fixed bug in parser, reporting position -1 for EOF

- src/inmanta/ast/attribute.py
- src/inmanta/ast/entity.py
- src/inmanta/ast/statements/define.py
- src/inmanta/ast/type.py
- src/inmanta/parser/plyInmantaParser.py
- tests/test_compilation.py
- tests/test_compiler.py
> added docstring to relations, typedef, implementation and implement

- src/inmanta/parser/plyInmantaLex.py
- src/inmanta/parser/plyInmantaParser.py
- tests/test_compiler.py
> fixed handling of newlines in MLS lexer mode

- src/inmanta/ast/__init__.py
- src/inmanta/ast/statements/__init__.py
- src/inmanta/ast/statements/define.py
- src/inmanta/execute/scheduler.py
- tests/conftest.py
- tests/test_compilation.py
- tests/test_compiler_errors.py
> added cycle detection in inheritance

- src/inmanta/ast/statements/call.py
- src/inmanta/ast/variables.py
- src/inmanta/execute/proxy.py
- src/inmanta/plugins.py
- tests/data/compile_plugin_typing/invalid.cf
- tests/data/compile_plugin_typing/libs/test/model/_init.cf
- tests/data/compile_plugin_typing/libs/test/module.yml
- tests/data/compile_plugin_typing/libs/test/plugins/__init__.py
- tests/data/compile_plugin_typing/main.cf
- tests/data/compile_plugin_typing/project.yml
- tests/test_compilation.py
> improved type annotations for plugins and improved object unwrapping

- src/inmanta/parser/plyInmantaParser.py
- tests/test_compiler.py
> added auto newline at end of file

- src/inmanta/main.py
fixes #208
the monitor command is still quite limited: if a second deploy is started, the progress bar will hang,...
> added monitor command to inmanta-cli

- src/inmanta/execute/runtime.py
- tests/test_compilation.py
> fixed resolver rest issue

- src/inmanta/parser/__init__.py
- src/inmanta/parser/plyInmantaParser.py
- tests/test_compilation.py
- tests/test_compiler_errors.py
> improved error reporting on parser errors

- src/inmanta/ast/statements/define.py
- tests/test_compiler_errors.py
> Add location to type not found exception in relation

- src/inmanta/agent/agent.py
- src/inmanta/server/agentmanager.py
(also fix for new auth framework using config api incorrectly)
> Allow agent instances to operate independently

- src/inmanta/ast/statements/define.py
- tests/test_compilation.py
> Added check for attribute redefinition within one entity

- src/inmanta/ast/statements/assign.py
- src/inmanta/parser/plyInmantaParser.py
- tests/test_compiler.py
fixes #496
may require more in depth testing
> changed parser to accept trailing ,

- src/inmanta/ast/entity.py
- src/inmanta/ast/statements/generator.py
- src/inmanta/execute/scheduler.py
- tests/test_compilation.py
also increased compiler iteration count
fixes #511
> Added fix for index issue

- src/inmanta/ast/type.py
- tests/test_compilation.py
> removed implicit string to number conversion

- src/inmanta/parser/plyInmantaLex.py
- tests/test_compiler.py
> added support for escapes in regex

- src/inmanta/ast/statements/generator.py
- tests/test_compiler_errors.py
> improved error reporting on for loops

- src/inmanta/ast/statements/assign.py
- src/inmanta/ast/variables.py
- src/inmanta/execute/runtime.py
- src/inmanta/parser/plyInmantaLex.py
- src/inmanta/parser/plyInmantaParser.py
- tests/test_compilation.py
- tests/test_compiler.py
fixes #587 
might have to be tested some more, even though the change should be limited to the operator itself
> added += operator for assignment to lists

- src/inmanta/ast/statements/assign.py
- src/inmanta/ast/variables.py
- tests/test_compilation.py
- tests/test_compiler.py
- tests/test_compiler_errors.py
fixes #596
for review: suggestions for improved error messages are welcome.
> fix in operator in typedefs

- src/inmanta/parser/plyInmantaLex.py
- tests/test_compiler.py
> added support for single quotes

- src/inmanta/ast/type.py
- tests/test_compilation.py
- tests/test_export_model.py
> added fix for string representation

- src/inmanta/execute/runtime.py
- tests/test_compiler_errors.py
> added improved error message for lower bound violations on relations

- docs/language.rst
- src/inmanta/ast/__init__.py
- src/inmanta/ast/statements/assign.py
- src/inmanta/parser/plyInmantaParser.py
- tests/test_compilation.py
- tests/test_compiler.py
- tests/test_compiler_errors.py
> added map lookup syntax

- src/inmanta/ast/variables.py
- tests/test_compilation.py
> added missing line numbers

- src/inmanta/ast/constraint/expression.py
- tests/test_compilation.py
> added in operator for dicts

- src/inmanta/ast/entity.py
- src/inmanta/ast/statements/define.py
- tests/test_compiler_errors.py
> improved error reporting on missing type

- src/inmanta/execute/runtime.py
- tests/test_compilation.py
> fixed bug in bounds check

- src/inmanta/agent/agent.py
- src/inmanta/methods.py
- src/inmanta/server/agentmanager.py
- tests/test_server_agent.py
> allowed get facts from undeployed or undefined resources 

- src/inmanta/env.py
related to https://github.com/pypa/pip/issues/5373
- fixes #727 by using `python -m pip` instead of `pip`
- fixes bug where output is not printed upon failure of pip
> improved pip stability and error reporting

- src/inmanta/config.py
- src/inmanta/server/config.py
- src/inmanta/server/server.py
These changes should move to the server extension that will integrate
LCM with the core.
> Add options to enable LCM support (tech preview)

- src/inmanta/server/server.py
- tests/conftest.py
- tests/test_deploy.py
> removed incorrect uninitialize of subprocess signal handler

- src/inmanta/env.py
- tox.ini
fixes missing re-raise on pip install making failures hard to resolve
> fixed missing re-raise on pip install 

- src/inmanta/app.py
wired through the fixes for #746  to the cli
> added improved error reporting to CLI

- CHANGELOG.md
- src/inmanta/export.py
- src/inmanta/server/server.py
- tests/test_server.py
- Catch various silent test failures
- Initialise variable for upload of version with no resources
- Raise exception on bad export to make inmanta export fail with exit status > 0
> Fix various silent test failures

- src/inmanta/server/server.py
> Fix lcm url generation for config.js

- CHANGELOG.md
- src/inmanta/ast/entity.py
- src/inmanta/ast/statements/generator.py
- tests/compiler/test_defaults.py
fixes #958
cleanup of default handling
> fixed bug in resolution of defaults

- src/inmanta/ast/statements/generator.py
- src/inmanta/parser/plyInmantaParser.py
- tests/compiler/test_defaults.py
> further cleanup of default processing

- src/inmanta/agent/agent.py
- src/inmanta/protocol/common.py
- src/inmanta/protocol/decorators.py
- src/inmanta/protocol/endpoints.py
- src/inmanta/protocol/rest/__init__.py
- src/inmanta/protocol/rest/server.py
- src/inmanta/server/agentmanager.py
- src/inmanta/server/protocol.py
- src/inmanta/util.py
- tests/conftest.py
- tests/test_server.py
- tests/test_server_agent.py
- tests/test_util.py
- Fix sid validation
- Make sure scheduler is stopped
- Test and type scheduler
- Fix tests
- Add test for call without sid
> Validate SID and shutdown

- CHANGELOG.md
- src/inmanta/ast/__init__.py
- src/inmanta/execute/scheduler.py
- tests/test_anchors.py
> added support for defaults to language server

- requirements.txt
solution for the build breakages
> added version lock to psycopg

- requirements.txt
- tests/test_app.py
Increase timers shutdown test cases to make sure that the signal handler is attached.
> Increase timers shutdown test cases

- CHANGELOG.md
- src/inmanta/agent/agent.py
- src/inmanta/protocol/methods.py
- src/inmanta/server/agentmanager.py
- src/inmanta/server/server.py
- tests/server/test_incremental_deploy.py
- tests/test_agent_manager.py
- tests/test_server.py
- tests/test_server_agent.py
> Ensured that only the primary agent can pull resources

- src/inmanta/data_pg.py
- src/inmanta/protocol/methods.py
- src/inmanta/server/server.py
- tests/test_project.py
Allow specification of project and environment id:
* Allow id in data objects
* Add optional argument to project and environment to specify the id
fixes #1001
> Issue/1001 project UUID

- src/inmanta/server/server.py
- tests/conftest.py
- tests/test_server_agent.py
perhaps requires some additional testing on full recompile mechanism
> fixes for recompile mechanism

- src/inmanta/server/server.py
- tests/test_form.py
Remove redundant query to the database in the update_record API call.
> Remove redundant code

- docs/guides/metering.rst
- docs/install.rst
> added documentation for performance metering

- src/inmanta/const.py
- src/inmanta/data.py
- src/inmanta/server/server.py
- tests/agent_server/conftest.py
- tests/agent_server/test_deploy_trigger.py
- tests/agent_server/test_server_agent.py
- tests/server/test_incremental_deploy.py
- tests/test_const.py
- tests/test_data.py
- tests/test_server.py
> added additional input validation to resource_action_update

- CHANGELOG.md
- Dockerfile
- docker-compose.yml
- misc/docker-server.cfg
> Update docker setup

- CHANGELOG.md
- src/inmanta/ast/constraint/expression.py
- src/inmanta/ast/statements/assign.py
- src/inmanta/execute/runtime.py
- tests/compiler/test_basics.py
- tests/compiler/test_dict.py
> improved error reporting on local variable conflicts

- CHANGELOG.md
- src/inmanta/ast/statements/define.py
- tests/compiler/test_basics.py
- tests/compiler/test_typedef.py
> fixed bug in typedef exception reporting

- src/inmanta/ast/statements/assign.py
- tests/compiler/test_dict.py
> add static evaluation to dict constructor

- docs/model_developers/test_plugins.rst
Add documentation on how to test an Inmanta plugin.
> Add documentation on how to test a plugin.

- setup.py
- tests/compiler/test_index.py
> Issue/1009 added description to setup.py

- src/inmanta/const.py
- src/inmanta/data/__init__.py
- tests/server/test_incremental_deploy.py
> added support for undeployable states in increment

- CHANGELOG.md
- src/inmanta/protocol/common.py
- src/inmanta/protocol/decorators.py
- src/inmanta/protocol/methods.py
- src/inmanta/protocol/rest/__init__.py
- tests/test_2way_protocol.py
- tests/test_protocol.py
Use path in methods instead of method_name + index + id
> Support path with variables in protocol

- CHANGELOG.md
- src/inmanta/config.py
- tests/conftest.py
to hook into clean_db mechanism
> added extension point in conftest for extensions 

- src/inmanta/app.py
- tests/test_app.py
Only show warning regarding missing config files/dirs when the server is started
> Fix warning regarding missing config files/dirs

- CHANGELOG.md
- src/inmanta/agent/handler.py
- src/inmanta/const.py
- src/inmanta/protocol/common.py
- src/inmanta/protocol/methods.py
- src/inmanta/protocol/rest/__init__.py
- src/inmanta/server/server.py
- src/inmanta/types.py
- src/inmanta/util.py
- tests/agent_server/conftest.py
- tests/test_const.py
- tests/test_protocol.py
> Getter handling

- src/inmanta/data/__init__.py
Work done on typing for verification of issue #1130. No fix was needed. This PR only contains improved typing.
> Improve typing of methods in data.Environment

- src/inmanta/server/bootloader.py
- src/inmanta/server/config.py
- src/inmanta/server/protocol.py
- src/inmanta_ext/core/extension.py
> Replace logic with wait_for

- src/inmanta/config.py
- src/inmanta/server/config.py
- src/inmanta/server/server.py
> Remove all config related to lcm prototype

- src/inmanta/app.py
- Fail deploy command if setup fails
- Also send server message to logs and not only stdout
> Improve error handling

- misc/inmanta.vim
updated vim syntax file to include regex, numbers, import and quote escapes in strings
> Vim syntax

- docs/platform_developers/create_server_extension.rst
Please also review the template: https://github.com/inmanta/inmanta-extension-template.
> Add documentation Inmanta extension template.

- src/inmanta/ast/type.py
reviewed normalization, after spotting potential issue
> reviewed normalization in the compiler

- CHANGELOG.md
- src/inmanta/moduletool.py
- tests/test_moduletool.py
> added proper closing of the project file

- CHANGELOG.md
- src/inmanta/agent/io/local.py
- tests/test_io.py
> Fixed exists in LocalIo for broken symlinks

- src/inmanta/agent/io/local.py
> Change FileNotFoundError() -> IOError()

- src/inmanta/ast/statements/generator.py
Cleanup of the If statement implementation. Now that I'm more familiar with the code base I spotted some uncleanliness in the implementation. This pull request should fix that.
> If statement cleanup

- misc/inmanta.vim
added missing keywords to the vim syntax file
> vim syntax file extension

- docs/model_developers/modules.rst
> Fix some grammar, add example for decorator arg

- tests_common/setup.py
> Set the common version correct

- src/inmanta/config.py
Old branch from wouter that I rebased so it can be merged in
> started typing config

- CHANGELOG.md
- src/inmanta/agent/handler.py
- tests/agent_server/test_evolution.py
Added logging to CRUD methods of handler and a diff method with context
> Add context to crud diff

- src/inmanta/agent/handler.py
- tests/test_agent.py
fixes #1493
Moving the additional test for cross test dependencies to another ticket.
> Also accept tuple with changes in handler

- src/inmanta/env.py
- tests/agent_server/test_evolution.py
- tests/agent_server/test_send_events.py
- tests/agent_server/test_server_agent.py
- tests/compiler/test_index.py
- tests/conftest.py
- tests/server/test_compilerservice.py
- tests/test_2way_protocol.py
- tests/test_app_cli.py
- tests/test_cache.py
- tests/test_server.py
- tests/utils.py
- tox.ini
Various tweaks in the test cases to speedup tests.
> Speed up tests

- pytest.ini
- src/inmanta/server/agentmanager.py
- tests/compiler/test_basics.py
- Removed pytest.ini
- Changed the wait_for_proc_bounded timout to const.SHUTDOWN_GRACE_HARD
- Add test that checks the compiler version (not None)
> Add compiler version test

- CHANGELOG.md
- src/inmanta/agent/handler.py
- tests/agent_server/test_resource_handler.py
Not sure if this is the only place this is required
> Verify hashes when serving a file. Closes #532

- src/inmanta/ast/statements/__init__.py
- tests/test_parser.py
> Render a boolean correct

- CHANGELOG.md
- src/inmanta/server/services/compilerservice.py
- tests/server/test_compilerservice.py
> Print extra env variables in init log and only store those in database

- CHANGELOG.md
- src/inmanta/plugins.py
> Add get_environment_id to plugin context

- src/inmanta/module.py
> Fix a typo in a message

- CHANGELOG.md
- src/inmanta/protocol/endpoints.py
- src/inmanta/server/protocol.py
- tests/test_server.py
> Fix warning about transport config

- docs/language.rst
> Update docs to clarify use of conditions

- CHANGELOG.md
- src/inmanta/export.py
- tests/test_app_cli.py
> Fixed inconsistent behavior of `export` and and `export -j`

- CHANGELOG.md
- src/inmanta/moduletool.py
- tests/moduletool/test_freeze.py
> Fixed bug where `module freeze` results in empty module.yml

- src/inmanta/data/model.py
- src/inmanta/server/extensions.py
- src/inmanta/server/server.py
- src/inmanta/server/services/formservice.py
- tests/test_extension_loading.py
An updated feature manager to also support non-boolean features. The code is also greatly simplified. The main driver for that is the license manager.
> updated feature manager

- docs/conf.py
- docs/reference/api.rst
- docs/reference/index.rst
api.rst was removed somewhere 12 months ago. this restores it.
fixes #1636
> Restore documentation file

- CHANGELOG.md
- src/inmanta/agent/handler.py
- tests/test_handler.py
additional test for crud handler behavior
> added test for crud handler behavior

- CHANGELOG.md
- src/inmanta/data/__init__.py
- tests/agent_server/test_dryrun.py
- tests/agent_server/test_server_agent.py
- tests/conftest.py
- tests/server/test_env_settings.py
- tests/server/test_purge_on_delete.py
- tests/test_app_cli.py
- tests/test_data.py
- tests/test_extension_loading.py
- tests/test_handler.py
> Update default environment settings

- CHANGELOG.md
- src/inmanta/server/services/environmentservice.py
- tests/agent_server/test_server_agent.py
> Resolve deadlock triggered by std::AgentConfigHandler

- CHANGELOG.md
- src/inmanta/export.py
> Add get_environment_id to exporter context

- CHANGELOG.md
- src/inmanta/main.py
- tests/test_cli.py
> Save .inmanta file for existing environment

- requirements.txt
- src/inmanta/protocol/openapi/__init__.py
- src/inmanta/protocol/openapi/converter.py
- src/inmanta/protocol/openapi/model.py
- src/inmanta/protocol/rest/server.py
- tests/test_openapi.py
- tox.ini
> Generate OpenAPI definition

- tests/test_app.py
This will increase the stability of the test cases.
> Increase timeouts in test cases

- src/inmanta/protocol/openapi/converter.py
- src/inmanta/protocol/openapi/model.py
- src/inmanta/types.py
- tests/test_cli.py
- tests/test_openapi.py
> Include pydantic types in OpenAPI definition

- inmanta.spec
I didn't see anything besides the spec file that needed updating, did I miss anything?
> Update spec file

- src/inmanta/protocol/methods_v2.py
- src/inmanta/server/server.py
- tests/test_openapi.py
> Add OpenAPI endpoint

- CHANGELOG.md
- src/inmanta/agent/handler.py
- tests/test_cache.py
This allows for connection cleanup
> added finalization support to @cache

- src/inmanta/agent/agent.py
- tests/agent_server/test_send_events.py
> Fix for Cross Agent Dependencies

- CHANGELOG.md
- src/inmanta/env.py
- src/inmanta/module.py
- tests/moduletool/test_python_dependencies.py
> Fix issue with parsing of requirements.txt in modules

- src/inmanta/parser/plyInmantaParser.py
Fixes 1 shift/reduce conflict and adds some abstraction to the dict parsing rules.
> Minor parser fixes

- CHANGELOG.md
- src/inmanta/ast/statements/define.py
These errors seem to be unreachable due to the implementation of the parser. Therefore I didn't add tests.
> fixed implementation for non-entity error message: fixes #1762

- src/inmanta/app.py
- src/inmanta/compiler/__init__.py
- src/inmanta/compiler/help/explainer.py
- src/inmanta/deploy.py
- src/inmanta/doctools.py
- src/inmanta/env.py
- src/inmanta/export.py
- src/inmanta/loader.py
- src/inmanta/main.py
- src/inmanta/module.py
- src/inmanta/moduletool.py
- src/inmanta/parser/plyInmantaParser.py
- src/inmanta/server/agentmanager.py
- src/inmanta/server/extensions.py
- src/inmanta/server/services/fileservice.py
- tests/conftest.py
- tests/moduletool/common.py
- tests/moduletool/test_freeze.py
- tests/moduletool/test_module_tool_basics.py
- tests/server/test_compilerservice.py
- tests/test_app.py
- tests/test_cli.py
- tests/test_config.py
- tests/test_deploy.py
- tests/test_io.py
- tests/test_jwt.py
- tests/test_loader.py
> Use correct encoding when handling files

- src/inmanta/protocol/rest/server.py
- tests/test_protocol.py
> Add authorization to allowed headers

- src/inmanta/protocol/openapi/converter.py
> Use correct server address for openapi

- .gitignore
- docs/Makefile
- docs/conf.py
- docs/reference/index.rst
- requirements.txt
- tests/extract_openapi_json.py
> Add openapi description to docs

- src/inmanta/protocol/rest/__init__.py
- tests/test_protocol.py
> Fix error for missing header

- CHANGELOG.md
- src/inmanta/moduletool.py
- tests/moduletool/test_module_tool_basics.py
> Improve moduletool robustness

- CHANGELOG.md
- src/inmanta/agent/reporting.py
- tests/test_agent.py
> Remove env vars from agent report

- src/inmanta/protocol/exceptions.py
- src/inmanta/server/server.py
- src/inmanta/server/services/databaseservice.py
- tests/conftest.py
- tests/server/test_server_status.py
> Handle database errors during server status call

- CHANGELOG.md
- src/inmanta/agent/agent.py
- src/inmanta/server/agentmanager.py
- src/inmanta/server/services/dryrunservice.py
- src/inmanta/server/services/resourceservice.py
- tests/conftest.py
- tests/test_server.py
> Use asyncio subprocess instead of tornado

- src/inmanta/export.py
- tests/data/modules/exp/model/_init.cf
- tests/data/modules/exp/plugins/__init__.py
- tests/test_export.py
fixes #1934
The Exceptions raised are not specific, but this is currently the case for all of the exporter
> Fixed dependency loop detection

- src/inmanta/compiler/__init__.py
- src/inmanta/execute/util.py
- src/inmanta/loader.py
- src/inmanta/module.py
- tests/conftest.py
- tests/data/modules/submodule/module.yml
- tests/data/modules/submodule/plugins/__init__.py
- tests/data/modules/submodule/plugins/pkg/__init__.py
- tests/data/modules/submodule/plugins/pkg/submod2.py
- tests/data/modules/submodule/plugins/submod.py
- tests/test_loader.py
Reverts inmanta/inmanta#1932 
due to unexpected failures in module tests
> Revert "Issue/507 support import submodules"

- CHANGELOG.md
- src/inmanta/data/schema.py
- src/inmanta/db/versions/v4.py
- tests/data/db/versions/v1.py
- tests/data/db/versions/v2.py
- tests/db/test_db_schema.py
> Add support for disabled flag in database migration scripts

- CHANGELOG.md
- src/inmanta/data/schema.py
- src/inmanta/db/versions/v1.py
- src/inmanta/db/versions/v2.py
- src/inmanta/db/versions/v3.py
- src/inmanta/db/versions/v5.py
- tests/db/dumps/v4.sql
- tests/db/test_db_schema.py
Adds v5 db migration script, with the disabled flag set to True.
closes #1914
> Add v5 db migration script

- docs/platform_developers/database.rst
> added documentation for #1958

- .github/pull_request_template.md
added strikethrough comment for non-applicable checkboxes to the pull request template
~~closes *Add ticket reference here*~~
> added strikethrough comment to PR template

- CHANGELOG.md
- docs/model_developers/model_debugging.rst
- src/inmanta/compiler/__init__.py
- src/inmanta/execute/dataflow/__init__.py
- src/inmanta/execute/dataflow/root_cause.py
- src/inmanta/execute/proxy.py
- src/inmanta/execute/runtime.py
- tests/compiler/dataflow/test_model_assignment.py
- tests/compiler/dataflow/test_model_root_cause.py
- tests/compiler/test_exception.py
Adds root cause analysis functionality to the compiler when compiled with the --enable-experimental-datatrace flag.
At this point, this pull request is not ready for full review yet. However, I would like some input on the clarity (and completeness of the definition if possible) of the `inmanta.execute.dataflow.root_cause` module. The self checklist below should give an overview of which parts still need work.
Note: I believe the efficiency of the root cause implementation could be greatly improved. I also believe the current implementation is quite understandable and efficiency is not really a concern here. Let me know if you think improving the efficiency would be worth the effort.
closes #1821
> data flow root cause analysis: fixes # 1821

- CHANGELOG.md
- src/inmanta/const.py
- src/inmanta/data/__init__.py
- src/inmanta/protocol/methods_v2.py
- src/inmanta/server/agentmanager.py
- tests/test_agent_manager.py
- tests/test_data.py
* Added support to agentmanager to pause an agent.
closes #1128 and #105
> Added support to pause agent

- CHANGELOG.md
- src/inmanta/protocol/openapi/converter.py
- src/inmanta/server/server.py
- tests/test_openapi.py
> Ensure correct version in api docs

- CHANGELOG.md
- src/inmanta/main.py
- src/inmanta/protocol/methods_v2.py
- tests/test_agent_manager.py
Replaces the '{}' characters to '<>' in the path, to handle them as path params
closes #2009 
> Fix agent_action path

- Dockerfile
- misc/epel.repo
Use newer version of nodejs on Dockerfile.
> Increase version nodejs

- src/inmanta/agent/config.py
> Fix error in documentation

- src/inmanta/execute/runtime.py
removed duplicate get_location set_location implementation in Instance
closes #1989
> removed duplicate get_location set_location implementation in Instance

- docs/reference/config.rst
Add missing config options in documentation.
> Add missing config options

- CHANGELOG.md
- src/inmanta/server/agentmanager.py
- tests/test_agent_manager.py
> Fix agent restart on env setting update

- CHANGELOG.md
- docs/reference/commands.rst
- src/inmanta/main.py
Adds further documentation to the inmanta-cli command and its subcommands
closes #2057 
> Document inmanta-cli

- CHANGELOG.md
- src/inmanta/config.py
> Document config option types

- CHANGELOG.md
- src/inmanta/protocol/openapi/converter.py
- src/inmanta/protocol/openapi/model.py
- tests/test_openapi.py
> Add method name as operationid to openapi

- CHANGELOG.md
- docs/platform_developers/exceptions.rst
- docs/reference/api.rst
- src/inmanta/data/schema.py
- src/inmanta/protocol/exceptions.py
> Documentation section about exceptions

- CHANGELOG.md
- src/inmanta/data/__init__.py
>  Extend documentation of autostarted agent settings 

- CHANGELOG.md
- src/inmanta/ast/attribute.py
- src/inmanta/ast/blocks.py
- src/inmanta/ast/entity.py
- src/inmanta/ast/statements/define.py
- src/inmanta/compiler/__init__.py
- src/inmanta/execute/runtime.py
- src/inmanta/execute/scheduler.py
- src/inmanta/plugins.py
Improved typing of compiler core
> Improved compiler typing

- tests/compiler/test_compile_export.py
Use tmp_path instead of tempfile.mkstemp in compiler json export tests so the temporary files get cleaned up afterwards.
closes #2095
> use tmp_path instead of tempfile.mkstemp in test

- misc/inmanta.vim
> added not as keyword to inmanta.vim

- CHANGELOG.md
- src/inmanta/agent/agent.py
- src/inmanta/protocol/rest/client.py
- tests/agent_server/test_server_agent.py
- tests/test_protocol.py
added fix for URL encoding problems in return channel 
closes 2134
I did some things in less conventional ways, hope you like it.
> added fix for URL encoding problems in returnchannel

- CHANGELOG.md
- src/inmanta/protocol/rest/server.py
- tests/test_protocol.py
> Report json decoding error

- CHANGELOG.md
- src/inmanta/agent/agent.py
- src/inmanta/agent/cache.py
- tests/test_cache.py
Fixed a leak in time based cache eviction
> removed leak of time based cache eviction

- CHANGELOG.md
- requirements.txt
- src/inmanta/server/agentmanager.py
- tests/test_agent_manager.py
- tests/utils.py
Fixes the agent crosstalk problem
closes #2163
> resolved issue in agent where crosstalk is possible

- CHANGELOG.md
- src/inmanta/agent/agent.py
- tests/test_agent.py
> Fix agent stuck in disabled state

- CHANGELOG.md
- src/inmanta/resources.py
- tests/test_resource.py
> Constrain agent names

- src/inmanta/protocol/methods.py
Fix error in the documentation of the `get_resource()` API call.
> Fix error in API documentation

- CHANGELOG.md
- src/inmanta/module.py
- tests/moduletool/test_python_dependencies.py
> Fix comments in requirements.txt

- CHANGELOG.md
- requirements.txt
- setup.py
- src/inmanta/main.py
Related to inmanta/lsm#103 and inmanta/inmanta-lsm#350
> Add support for inmanta-cli click plugins

- CHANGELOG.md
- docs/index.rst
Added link to the PDF version of the documentation.
> Added link to the PDF version of the documentation

- CHANGELOG.md
- src/inmanta/data/__init__.py
- src/inmanta/data/model.py
- src/inmanta/db/versions/v5.py
- src/inmanta/protocol/common.py
- src/inmanta/protocol/methods.py
- src/inmanta/server/services/resourceservice.py
- tests/test_data.py
- tests/test_server.py
closes inmanta/inmanta-telco#52
> Add API to query resource actions

- CHANGELOG.md
- src/inmanta/data/__init__.py
- src/inmanta/server/services/orchestrationservice.py
- tests/agent_server/test_server_agent.py
> Add environment setting for agent_trigger_method

- src/inmanta/protocol/methods.py
- src/inmanta/protocol/methods_v2.py
- src/inmanta/server/services/compilerservice.py
- src/inmanta/server/services/resourceservice.py
> Move new methods to v2

- src/inmanta/db/versions/v6.py
- tests/db/dumps/v5.sql
Added DB dump for schema v5.sql
> Add DB dump for schema v5.sql

- docs/platform_developers/platform.rst
Fix broken link in documentation.
> Fix broken link in documentation

- tests/db/dumps/v6.sql
- tests/db/test_v5_to_v6.py
> Add DB dump v6.sql

- CHANGELOG.md
- src/inmanta/server/services/compilerservice.py
- tests/server/test_compilerservice.py
> Fix server-autorecompile-wait

- CHANGELOG.md
- src/inmanta/app.py
- tests/moduletool/test_module_tool_basics.py
> Fix version cli argument conflict

- CHANGELOG.md
- docs/install/install-server/configure-postgres.inc
- docs/install/install-server/configure-server.inc
These install documentation tickets are small and related to each other:
closes #2241 
closes #2356 
closes #2357 
> Enhance install documentation

- docs/model_developers/modules.rst
minor module.yml documentation fixes
> minor module.yml documentation fixes

- CHANGELOG.md
- src/inmanta/loader.py
- tests/test_loader.py
Don't load all code on agent start
closes #2343
> Don't load all code on agent start

- src/inmanta/execute/proxy.py
make sequenceproxy a list to avoid surprises
> make sequenceproxy a list to avoid surprises

- CHANGELOG.md
- src/inmanta/parser/plyInmantaParser.py
- tests/test_parser.py
allow empty else branch
closes #2375
> allow empty else branch

- CHANGELOG.md
- docs/model_developers.rst
- docs/model_developers/configurationmodel.rst
- docs/model_developers/modules.rst
- docs/model_developers/test_plugins.rst
- docs/reference/projectyml.rst
I did this cleanup in preparation for some other docs changes 
1. fixed some dead links
2. renamed a few sections to be clearer
3. fixed order in the menu to logical order (instead of alphabetical)
4. added coockiecutter to project guide
> Minor cleanup of model developer documentation

- CHANGELOG.md
- src/inmanta/ast/attribute.py
- src/inmanta/ast/statements/define.py
- tests/compiler/test_define.py
- tests/compiler/test_slots.py
- tests/test_type.py
improved duplicate attribute error message
closes #2386
> improved duplicate attribute error message

- setup.py
Fix install by adding dependency to core
> Add more-itertools to runtime dep

- src/inmanta/db/versions/v8.py
- tests/db/dumps/v7.sql
Add db dump for version 7 of the database schema.
> Add db dump file.

- .github/dependabot.yml
- requirements.txt
Downgrade to pytest-postgresql and prevent it from being updated by dependabot.
> Downgrade pytest-postgresql

- .gitignore
- src/inmanta/server/services/compilerservice.py
Changing logging level for compile export failure in CompilerService.
closes #2377 
> Changing logging level

- tests/test_compiler_entrypoints.py
> fixed failing test

- CHANGELOG.md
- src/inmanta/server/services/compilerservice.py
- tests/server/test_compilerservice.py
Ensure the compiler service takes into account the environment variables set on the system
closes #2413
> Ensure the compiler service takes into account the environment variables set on the system

- src/inmanta/server/config.py
> fixed incorrect option reference in docstring

- CHANGELOG.md
- src/inmanta/agent/agent.py
- src/inmanta/server/services/resourceservice.py
- tests/agent_server/test_send_events.py
> Fix for cross agent dependencies responding to unavailable resources

- CHANGELOG.md
- src/inmanta/export.py
- tests/test_app_cli.py
Other failures (than the missing environment) were already not silent
closes #2487 
> Export command should raise exception on failure

- docs/check_sphinx.py
- pytest.ini
- tox.ini
> Fix failing test, fix pytest mark warning

- CHANGELOG.md
- src/inmanta/__init__.py
- src/inmanta/module.py
- src/inmanta/util.py
- tests/compiler/test_basics.py
Decouple compiler version from OSS product version.
closes #2573
> Decouple compiler version from OSS product version

- CHANGELOG.md
- src/inmanta/app.py
- src/inmanta/protocol/openapi/converter.py
- src/inmanta/server/bootloader.py
- src/inmanta/server/extensions.py
- src/inmanta/server/protocol.py
- src/inmanta/server/server.py
- tests/test_app.py
Show versions of all installed components when running `inmanta --version`.
closes #2574
> Show versions of all installed components when running inmanta --version

- docs/install/2-configure-agents.rst
- docs/install/install-server/install-server.inc
Install `epel-release` before the installation of the inmanta packages as such that the dependent package `openssl11` gets resolved.
> Update release doc to install epel-release on Centos7

- CHANGELOG.md
- docs/install/install-server/install-server.inc
- setup.py
- src/inmanta/server/extensions.py
- src/inmanta/server/protocol.py
Renames the inmanta package to inmanta-core
part of inmanta/irt#363
> renamed inmanta package to inmanta-core

- .bumpversion.cfg
Set version in .bumpversion.cfg to 4.0.0
> Fix version number in .bumpversion.cfg

- inmanta.spec
Updates inmanta.spec to build python3-inmanta-core correctly
Part of inmanta/inmanta-core#2589. Requires inmanta/irt#380.
> Inmanta core rename rpm package

- CHANGELOG.md
- src/inmanta/server/extensions.py
Ensure the Inmanta OSS product version is reported correctly
closes #2622
> Ensure the Inmanta OSS product version is reported correctly

- CHANGELOG.md
- src/inmanta/server/extensions.py
Same change as #2641 but merge will happen on iso4. 
closes #2622
> Ensure the Inmanta OSS product version is reported correctly (#2641)

- .bumpversion.cfg
- tests_common/setup.py
> new versioning scheme for pytest-inmanta-extensions

- docs/install/2-configure-agents.rst
- docs/install/install-server/install-server.inc
part of inmanta/irt#441
I'll cherry-pick this on iso4 but not on iso3 when this is merged.
> updated RPM names in docs

- tests_common/setup.py
> Fix a typo in the name

- requirements.txt
pyformance is also a dep of core, it is only part of dev deps at the moment.
> Pyformance is also a dep

- requirements.setup.txt
Add `requirements.setup.txt` file.
> Add requirements.setup.txt file (#2687)

- src/inmanta/env.py
- src/inmanta/module.py
- tests/conftest.py
- tests/moduletool/test_python_dependencies.py
- tests/test_env.py
- tests/test_loader.py
This PR:
* Fixes some bugs in the test cases.
* Makes the `VirtualEnv` more robust.
> Fix bugs in test cases

- src/inmanta/env.py
- src/inmanta/module.py
- tests/conftest.py
- tests/moduletool/test_python_dependencies.py
- tests/test_env.py
- tests/test_loader.py
> Fix bugs in test cases (#2690)

- .bumpversion.cfg
Added explicit search-replace to `.bumpversion.cfg`. I will cherry-pick this onto the iso branches.
> added explicit search-replace

- requirements.dev.txt
Pin pytest-inmanta-extensions package.
> Pin pytest-inmanta-extensions package

- docs/Makefile
- docs/administrators/auth.rst
- docs/administrators/metering.rst
- docs/check_sphinx.py
- docs/conf.py
- docs/index.rst
- docs/troubleshooting.rst
- pytest.ini
- requirements.txt
- tox.ini
Cherry-pick several fixes documentation related fixes from the master branch:
* Fix broken links.
* Don't run link check by default in tox.
* Add support to disable version discovery.
> Cherry-pick several fixes documentation related fixes from master

- requirements.dev.txt
Remove dev dependency on pytest-inmanta-extensions.
> Remove dev dependency on pytest-inmanta-extensions

- tests_common/setup.py
Pin inmanta version in pytest-inmanta-extensions package.
> Pin inmanta version in pytest-inmanta-extensions package

- tests_common/setup.py
Pin inmanta-core version in pytest-inmanta-extensions package.
> Pin inmanta-core version in pytest-inmanta-extensions package

- tests/conftest.py
- tests/server/test_compilerservice.py
Fix race condition in tests cases of compiler service.
> Fix race condition in tests cases of compiler service (#2725)

- docs/Makefile
Install openapi dependencies from constraint file.
> Install openapi dependencies from constraint file (#2735)

- CHANGELOG.md
- src/inmanta/agent/io/local.py
- tests/conftest.py
Prevent KeyError on PYTHONPATH
Part of #2747
> Prevent KeyError on PYTHONPATH (#2748)

- CHANGELOG.md
- docs/install/install-server/install-server.inc
This PR adds the following changes to the installation documentation:
* Use the packages.inmanta.com RPM repository instead of pkg.inmanta.com
* Add installation procedure for Centos 8.
> Update installation documentation

- CHANGELOG.md
- docs/install/install-server/install-server.inc
Update installation documentation.
> Update installation documentation (#2751)

- src/inmanta/env.py
- tests/test_env.py
Fix python path inheritance for virtual envs.
Part of #2650
> Fix python path inheritance for virtual envs (#2651)

- CHANGELOG.md
- changelogs/unreleased/cherry-pick-api-result-limit.yml
- src/inmanta/data/__init__.py
- src/inmanta/db/versions/v7.py
- src/inmanta/protocol/methods.py
- src/inmanta/protocol/methods_v2.py
- src/inmanta/server/agentmanager.py
- src/inmanta/server/services/compilerservice.py
- src/inmanta/server/services/orchestrationservice.py
- src/inmanta/server/services/resourceservice.py
- tests/db/dumps/v6.sql
- tests/db/test_db_schema.py
- tests/db/test_v6_to_v7.py
- tests/server/test_compilerservice.py
- tests/test_agent_manager.py
- tests/test_data.py
Cherry-picked 6f95f6c.
We found out that some patches intended for ISO3 never made it into ISO3 
I will cherry-pick this to `iso3-next`
> Iso3 db v7 cherry picks api results

- .bumpversion.cfg
- tests_common/setup.py
Pin internal dependencies.
Part of inmanta/irt#528
> Pin internal dependencies

- setup.py
- tests_common/setup.py
Another fix to the module sets issue
> Fixed iso3 package for matched install

- changelogs/unreleased/417-add-changelog-to-docs.yml
- docs/changelogs.rst
- docs/conf.py
- docs/index.rst
- requirements.dev.txt
- requirements.txt
Revert PR #2883. I can merge this in directly, I assume?
> Revert adding changelog section to iso3

- changelogs/unreleased/pin-docstring-parser.yml
- setup.py
> Add upperbound to docstring-parser dependency (PR #2979)

- changelogs/unreleased/3668-dryrun-diff.yml
- changelogs/unreleased/3771-improve-dryrun-naming.yml
- changelogs/unreleased/fix-test-for-std-2.1.11.yml
- changelogs/unreleased/inmanta-version-fix.yml
- src/inmanta/app.py
- src/inmanta/data/model.py
- src/inmanta/protocol/methods_v2.py
- src/inmanta/server/diff.py
- src/inmanta/server/services/dryrunservice.py
- src/inmanta/server/services/orchestrationservice.py
- tests/agent_server/test_dryrun.py
- tests/moduletool/test_add.py
- tests/moduletool/test_install.py
Cherry-picks for the iso5 release. For review it might be easiest to just look at the change entries.
@andraskvr have I got everything from the frontend (no changes required on the web-console repo)?
> Iso5 rc cherry picks

- src/inmanta/data/paging.py
How about this? I'm not familiar with and have not looked into the broader semantics of this code so let me know if something does not make sense. Should I include @andraskvr?
Mypy diff is empty.
> use generics for typing fixes

- docs/lsm/embedded_entities/embedded_entities.rst
> added procedure docs

- src/inmanta/deploy/scheduler.py
pass control to IO loop less often
I don't love the verbosity, but I don't see a way around it.
> pass control to IO loop less often

- tests/deploy/test_timer_handling.py
As reported on [Slack](https://inmanta.slack.com/archives/CKRF0C8R3/p1736947521192539)
> fixed race in timer tests

- changelogs/unreleased/bump-compiler-version-to-2025-4.yml
- src/inmanta/__init__.py
> Bump compiler version 2024.4

- changelogs/unreleased/8193-add-new-database-connection-pool-setting.yml
- changelogs/unreleased/8197-final-api-cleanup.yml
- changelogs/unreleased/8340-add-blocked-status-transient.yml
1. is there a way to test this? Some things didn't render correct before, I hope they will now
2. I suppose I have to merge this by hand? 
> Cleaned up changelog

- tests/test_env.py
Cherry-picked this change from iso8. I'll merge with the merge button and cherry-pick the merge commit to the stable branch.
> fixed test that has different behavior when wheel is not installed

- src/inmanta/data/__init__.py
- src/inmanta/deploy/persistence.py
- src/inmanta/deploy/scheduler.py
- tests/server/test_resource_list.py
> refactored test to have scheduler update resource state

- .bumpversion.cfg
- setup.py
- src/inmanta/__init__.py
- tests_common/setup.py
> bump version to 11.5.3

- src/inmanta/__init__.py
> bump COMPILER_VERSION to 2025.4

- src/inmanta/data/model.py
Trimmed down BaseModel after recent changes. The remaining config and comment seemed to imply something special is going on, while we removed the special that was there.
> trimmed down BaseModel

- docs/adr/0002-database-upgrade-testing.md
Added some info regarding the dump process
> add some info regarding the dump
